import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// 引入 Provider
import { ThemeProvider } from "@/components/theme-provider"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* 在 html 标签加 suppressHydrationWarning 可以消除深色模式的水合警告 */}
      <body className={inter.className}>
        {/* 包裹 Provider，关键配置如下 */}
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}